# ----------- Build Stage -----------
FROM golang:1.22 AS builder

# Enable Go modules and set working directory
WORKDIR /controller

# Cache go.mod and go.sum first (faster builds)
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the code
COPY . .

# Build the binary
# For webhook use:   go build -o webhook main.go
# For controller use: go build -o controller controller.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -o controller oneagent-controller.go

# ----------- Runtime Stage -----------
FROM gcr.io/distroless/base-debian12

WORKDIR /

# Copy binary from builder
COPY --from=builder /controller/controller /controller

# TLS certs will be mounted as secrets in /tls
USER nonroot:nonroot

ENTRYPOINT ["/controller"]

