apiVersion: v1
kind: Namespace
metadata:
  name: pvc-webhook-ns

---
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1kZXYuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS1kb2NrZXItaHViLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImFydGlmYWN0b3J5LWVkZ2Uua3JvZ2VyLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV4TkRNNmNVbFBSbWxOVVRkMWNIRnRlalJhZGsxTFpFZGhlbTAxUVZCcyIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYaE9SRTAyWTFWc1VGSnRiRTVWVkdReFkwaEdkR1ZxVW1Ga2F6Rk1Xa1ZrYUdWdE1ERlJWa0p6IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWVmZm8tZG9ja2VyLWxvY2FsLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktY29uZmx1ZW50LWRvY2tlci1yZW1vdGUuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS1kb2NrZXItYmludHJheS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1lbGFzdGljLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktZG9ja2VyLWdjci5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1nY3ItazhzLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktZG9ja2VyLWh1Yi5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1pby5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1pby5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1tY3IuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS1kb2NrZXItcXVheS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1xdWF5LXl1Z2FieXRlLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktZG9ja2VyLXJlZ2lzdHJ5LXJlbW90ZS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci10a2cuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS1naXRodWItZG9ja2VyLXJlbW90ZS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWV1LWdjci1pby1yZW1vdGUuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS11cy1kZXYtcmVtb3RlLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktYXp1cmUtbWFya2V0cGxhY2UtcmVtb3RlLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktZG9ja2VyLWV2ZXJzZWVuLXJlbW90ZS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1yZWdpc3RyeS1yZWxlYXNlcy1yZW1vdGUuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS10b3NoaWJhLWVsZXJhLXJlbW90ZS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1sb2NhbC5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwgICAgICAgICAgICAgCiAgICAia3JvZ2VydGVjaG5vbG9neS1kb2NrZXItcmVtb3RlLmpmcm9nLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiczk5ODVqZnJvZ1BAa3JvZ2VyLmNvbSIsCiAgICAgICJwYXNzd29yZCI6ICJjbVZtZEd0dU9qQXhPakUzTmpRM056RXpORGc2TTBoRFdUWTFhWGxKVXpOU1QzcFBXV1J0TUVoS1kxWnViRUl6IiwKICAgICAgImF1dGgiOiAiY3prNU9EVnFabkp2WjFCQWEzSnZaMlZ5TG1OdmJUcGpiVlp0WkVkMGRVOXFRWGhQYWtVelRtcFJNMDU2UlhwT1JHYzJUVEJvUkZkVVdURmhXR3hLVlhwT1UxUXpjRkJYVjFKMFRVVm9TMWt4V25WaVJVbDYiCiAgICB9LAogICAgImtyb2dlcnRlY2hub2xvZ3ktZG9ja2VyLXRlc3QuamZyb2cuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzOTk4NWpmcm9nUEBrcm9nZXIuY29tIiwKICAgICAgInBhc3N3b3JkIjogImNtVm1kR3R1T2pBeE9qRTNOalEzTnpFek5EZzZNMGhEV1RZMWFYbEpVek5TVDNwUFdXUnRNRWhLWTFadWJFSXoiLAogICAgICAiYXV0aCI6ICJjems1T0RWcVpuSnZaMUJBYTNKdloyVnlMbU52YlRwamJWWnRaRWQwZFU5cVFYaFBha1V6VG1wUk0wNTZSWHBPUkdjMlRUQm9SRmRVV1RGaFdHeEtWWHBPVTFRemNGQlhWMUowVFVWb1Mxa3hXblZpUlVsNiIKICAgIH0sCiAgICAia3JvZ2VydGVjaG5vbG9neS1kb2NrZXItcHJvZC5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfSwKICAgICJrcm9nZXJ0ZWNobm9sb2d5LWRvY2tlci1zdGFnZS5qZnJvZy5pbyI6IHsKICAgICAgInVzZXJuYW1lIjogInM5OTg1amZyb2dQQGtyb2dlci5jb20iLAogICAgICAicGFzc3dvcmQiOiAiY21WbWRHdHVPakF4T2pFM05qUTNOekV6TkRnNk0waERXVFkxYVhsSlV6TlNUM3BQV1dSdE1FaEtZMVp1YkVJeiIsCiAgICAgICJhdXRoIjogImN6azVPRFZxWm5KdloxQkFhM0p2WjJWeUxtTnZiVHBqYlZadFpFZDBkVTlxUVhoUGFrVXpUbXBSTTA1NlJYcE9SR2MyVFRCb1JGZFVXVEZoV0d4S1ZYcE9VMVF6Y0ZCWFYxSjBUVVZvUzFreFduVmlSVWw2IgogICAgfQogICB9CiAgfQkgIAkgIAo=
kind: Secret
metadata:
  name: jfrog-secret
  namespace: pvc-webhook-ns
type: kubernetes.io/dockerconfigjson

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    servicenow.kroger.com/primary-support-group: INF-InStoreCloud
    certs.kroger.com/KeyfactorID: "569161"
  labels:
    app: pvc-webhook
  name: pvc-webhook-svc-cert
  namespace: pvc-webhook-ns
spec:
  commonName: pvc-webhook-ns.svc.cluster.local
  dnsNames:
  - pvc-webhook-ns.svc.cluster.local
  - pvc-webhook-svc.pvc-webhook-ns.svc.cluster.local
  - pvc-webhook-svc
  duration: 8760h
  issuerRef:
    group: certs.kroger.com
    kind: KrogerIssuer
    name: krogerissuer
  renewBefore: 720h
  secretName: pvc-webhook-tls
  subject:
    countries:
    - US
    localities:
    - Cincinnati
    organizationalUnits:
    - Kroger Technology & Digital
    organizations:
    - The Kroger Co.
    provinces:
    - Ohio

---
apiVersion: v1
kind: Service
metadata:
  name: pvc-webhook-svc
  namespace: pvc-webhook-ns
  annotations:
    cert-manager.io/issuer: "krogerissuer"
    cert-manager.io/certificate-name: "emptydir2pvc-svc-cert" # <<!nav>>Certificate<<!/nav>>
  labels:
    app: pvc-webhook
spec:
  selector: pvc-webhook
  ports:
  - name: https
    port: 443
    targetPort: 9443

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-webhook-sa
  namespace: pvc-webhook-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-webhook
  namespace: pvc-webhook-ns
  labels:
    app: pvc-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pvc-webhook
  template:
    metadata:
      labels:
        app: pvc-webhook
    spec:
      imagePullSecrets:
        - name: jfrog-secret
      containers:
        - name: pvc-webhook
          image: krogertechnology-docker-dev.jfrog.io/ecs_docker_repo/epmtydir2pvc/epmtydir2pvc:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: DEFAULT_SIZE
            value: "2Gi"
          - name: DEFAULT_STORAGE_CLASS
            value: "robin-repl-3"
          - name: DEFAULT_ACCESS_MODES
            value: "ReadWriteOnce"
          ports:
          - name: https
            containerPort: 9443
          volumeMounts:
            - name: webhook-certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: pvc-webhook-tls
---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pvc-webhook-webhook
  annotations:
    cert-manager.io/inject-ca-from: pvc-webhook-ns/pvc-webhook-svc-cert
  labels:
    app: pvc-webhook
webhooks:
- name: pvc-webhook.pvc-webhook-ns.svc
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Equivalent
  reinvocationPolicy: IfNeeded
  clientConfig:
    service:
      name: pvc-webhook-svc
      namespace: pvc-webhook-ns
      path: "/mutate"
      port: 443
    #caBundle: ${CA_BUNDLE_BASE64} # cert-manager can inject via patch or use cainjector if available
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE","UPDATE"]
    resources: ["pods"]
    scope: "*"
  objectSelector:
    matchExpressions:
    - key: pvc-webhook/enabled
      operator: In
      values: ["true"]
